import { gameReducer } from '../reducers/gameReducer.ts'
import { createInitialGame } from './createInitialGame.ts'
import { simulateMatch } from './simulateMatch.ts'
import { opponents } from '../data/opponents.ts'

const game = gameReducer(createInitialGame(), { type: 'RESOLVE_WEEKLY_ACTIVITY', choice: { id: 'rest' }, rolls: { development: 0, event: 0.9, player: 0 } })!
game.championAssignments = { Top: 'brannoch', Jungle: 'nyssik', Mid: 'threnna', Carry: 'serrune', Support: 'mirethi' }
game.selectedStrategyId = 'objective-control'
const report = simulateMatch(game, { timing: 0.312, player: 0.721, outcome: 0.46 }, opponents[1])!

console.log('# Match Engine V2 — generated example\n')
console.log('Generated by `npm run example:match` using Rest, Objective Control and the listed champion assignments. Opponent: Meridian Keepers. Random inputs: timing 0.312, player 0.721, outcome 0.46.\n')
console.log('Line-up: Taren Vossel — Brannoch; Nemi Corven — Nyssik; Iver Dalmere — Threnna; Sela Rennick — Serrune; Oren Valsett — Mirethi.\n')
for (const event of report.events) {
  const seconds = event.seconds!
  const time = `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`
  console.log(`**${time}** — ${event.text}\n`)
}
console.log(`**${report.result === 'victory' ? 'Victory' : 'Defeat'}**\n`)
